[project]
name = "discord-bot"
version = "0.1.0"
requires-python = "^>=3.10"
dependencies = [
  "discord.py^>=2.3.2",
  "python-dotenv^>=1.0.1",
]

[tool.ruff]
line-length = 100

[tool.black]
line-length = 100
